set_parameters <- function(parameters, other_prior, method){
  if(!requireNamespace("Hmisc", quietly = TRUE)){
    message("Install Hmisc...")
    utils::install.packages('Hmisc')
  }
  class_name <- paste0(Hmisc::capitalize(method), "Params")
  # whether the parameters are generated by Splatter
  alternative_methods <- c("SCRIP",
                           "ESCO",
                           "scDD",
                           "BASiCS",
                           "SparseDC",
                           "MFA")
  if(class(parameters) == class_name | method %in% alternative_methods){
    # match names in other_prior and in parameters
    index <- methods::slotNames(parameters)[stats::na.omit(match(names(other_prior),
                                                                 methods::slotNames(parameters)))]
    # filter
    other_prior <- other_prior[index]
    # reset customed paramters
    parameters <- splatter::setParams(parameters, other_prior)
    # return
    return(parameters)
  }else{
    return(parameters)
  }
}
